import unittest
from unittest.mock import AsyncMock, patch

from providers.openai_client import OPENAI_CHAT_MODEL
from services import code_generator
from services.code_generator import (
    CODE_MODEL,
    extract_unified_diff,
    select_code_generation_provider,
)


class CodeGeneratorOutputTests(unittest.TestCase):
    def test_code_generation_uses_gpt_56_sol(self):
        self.assertEqual(OPENAI_CHAT_MODEL, "gpt-5.6-terra")
        self.assertEqual(CODE_MODEL, "gpt-5.6-sol")

    def test_explicit_fable_directive_selects_claude(self):
        for request in (
            "claude edit your code",
            "Fable, change the repository",
            "use Claude to refactor your routing",
            "have fable fix the bot source",
        ):
            with self.subTest(request=request):
                self.assertEqual(select_code_generation_provider(request), "claude")

    def test_mentions_about_claude_do_not_select_it_as_generator(self):
        self.assertEqual(
            select_code_generation_provider("change your code so Claude chat has a timeout"),
            "openai",
        )


class ProviderAwareCodeGenerationTests(unittest.IsolatedAsyncioTestCase):
    async def test_claude_directive_uses_fable_for_patch(self):
        diff = """diff --git a/bot/response_policy.py b/bot/response_policy.py
--- a/bot/response_policy.py
+++ b/bot/response_policy.py
@@ -1 +1 @@
-import re
+import re  # generated by fable
"""
        context = [("bot/response_policy.py", "import re\n")]
        with patch.object(
            code_generator,
            "plan_code_context",
            new=AsyncMock(return_value=(context, {"selection": "model_planner"})),
        ), patch.object(
            code_generator,
            "_generate_code_response",
            new=AsyncMock(return_value=(diff, "claude-fable-5")),
        ) as generate:
            patch_text, metadata = await code_generator.generate_code_patch(
                "claude edit your code", "a" * 40
            )

        self.assertEqual(patch_text, diff)
        self.assertEqual(metadata["provider"], "claude")
        self.assertEqual(metadata["model"], "claude-fable-5")
        self.assertEqual(generate.await_args.kwargs["provider"], "claude")

    def test_extracts_fenced_unified_diff(self):
        text = """Here is the patch:
```diff
diff --git a/bot/response_policy.py b/bot/response_policy.py
--- a/bot/response_policy.py
+++ b/bot/response_policy.py
@@ -1 +1 @@
-import re
+import re  # generated
```
"""
        patch = extract_unified_diff(text)
        self.assertTrue(patch.startswith("diff --git "))
        self.assertIn("bot/response_policy.py", patch)

    def test_rejects_protected_generated_patch(self):
        text = """diff --git a/config.py b/config.py
--- a/config.py
+++ b/config.py
@@ -1 +1 @@
-import os
+import sys
"""
        with self.assertRaisesRegex(ValueError, "violated policy"):
            extract_unified_diff(text)

    def test_rejects_prose_without_diff(self):
        with self.assertRaisesRegex(ValueError, "unified Git diff"):
            extract_unified_diff("I would change several files.")


if __name__ == "__main__":
    unittest.main()
