const state={filter:"all",query:"",data:null};
const labels={all:"All",open:"Open",active:"Active",rejected:"Rejected",rolled_back:"Rolled back",failed:"Failed"};
const openStates=new Set(["draft","patch_uploaded","reviewable","approved"]);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const formatDate=value=>value?new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"—";
function effective(p){return p.deployment_status||p.status}
function statusLabel(s){return ({reviewable:"awaiting owner approval",approved:"approved / queued",patch_uploaded:"validation pending",validation_failed:"validation failed"})[s]||s.replaceAll("_"," ")}
function matchesFilter(p){const s=effective(p);if(state.filter==="all")return true;if(state.filter==="open")return openStates.has(p.status)&&!p.deployment_status;if(state.filter==="failed")return s==="failed"||p.status==="validation_failed";return s===state.filter}
function renderMetrics(items){const counts={total:items.length,reviewable:items.filter(p=>p.status==="reviewable"&&!p.deployment_status).length,active:items.filter(p=>effective(p)==="active").length,rejected:items.filter(p=>p.status==="rejected"||p.status==="validation_failed").length};document.querySelector("#metrics").innerHTML=[["Total changes",counts.total],["Awaiting owner approval",counts.reviewable],["Active releases",counts.active],["Rejected / failed",counts.rejected]].map(([l,v])=>`<div class="metric"><span>${l}</span><strong>${v}</strong></div>`).join("")}
function render(){const items=state.data.proposals.filter(p=>matchesFilter(p)).filter(p=>!state.query||`${p.summary} ${p.files.join(" ")} ${p.id}`.toLowerCase().includes(state.query));const root=document.querySelector("#changes");root.innerHTML=items.map(p=>{const s=effective(p);return `<article class="change"><div class="number">${esc(p.id)}</div><div><p class="summary">${esc(p.summary)}</p><div class="meta"><span>created ${esc(formatDate(p.created_at))}</span><span>baseline <code>${esc(p.baseline)}</code></span>${p.patch?`<span>patch <code>${esc(p.patch)}</code></span>`:""}</div>${p.files.length?`<div class="files">${p.files.map(f=>`<span class="chip">${esc(f)}</span>`).join("")}</div>`:""}</div><div class="state"><span class="badge ${esc(s)}">${esc(statusLabel(s))}</span>${p.deployment_result?`<span class="result">${esc(p.deployment_result)}</span>`:""}</div></article>`}).join("");document.querySelector("#empty").hidden=items.length>0}
function setupFilters(){const root=document.querySelector("#filters");root.innerHTML=Object.entries(labels).map(([k,v])=>`<button data-filter="${k}" class="${k==="all"?"active":""}">${v}</button>`).join("");root.addEventListener("click",e=>{if(!e.target.dataset.filter)return;state.filter=e.target.dataset.filter;root.querySelectorAll("button").forEach(b=>b.classList.toggle("active",b===e.target));render()});document.querySelector("#search").addEventListener("input",e=>{state.query=e.target.value.trim().toLowerCase();render()})}
fetch("data/changes.json",{cache:"no-store"}).then(r=>{if(!r.ok)throw Error(r.status);return r.json()}).then(data=>{state.data=data;document.querySelector("#baseline").textContent=data.baseline;document.querySelector("#updated").textContent=`Updated ${formatDate(data.generated_at)}`;renderMetrics(data.proposals);setupFilters();render()}).catch(()=>{document.querySelector("#updated").textContent="Ledger unavailable";document.querySelector("#empty").hidden=false;document.querySelector("#empty").textContent="The sanitized change ledger could not be loaded."});
